In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv(r'C:\Users\Shri_Ram\Downloads\healthcare\train_data.csv')
df.head()

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   
2        3             10                  e                   1   
3        4             26                  b                   2   
4        5             26                  b                   2   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   
2                    X                                  2    anesthesia   
3                    Y                                  2  radiotherapy   
4                    Y                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   
2         S                  E        2.0      31397                7.0   
3         R                  D        2.0      31397                7.0   
4         S                  D        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   
2            Trauma             Extreme                      2  51-60   
3            Trauma             Extreme                      2  51-60   
4            Trauma             Extreme                      2  51-60   

   Admission_Deposit   Stay  
0             4911.0   0-10  
1             5954.0  41-50  
2             4745.0  31-40  
3             7272.0  41-50  
4             5558.0  41-50

In [3]:
def convert_age_to_num(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0])+float(tokens[1]))/2
    try:
        return float(x)
    except:
        return None

In [4]:
convert_age_to_num('5625')

5625.0

In [5]:
convert_age_to_num('51-60')

55.5

In [6]:
convert_age_to_num('41-50')

45.5

In [7]:
df['Stay'].unique()

array(['0-10', '41-50', '31-40', '11-20', '51-60', '21-30', '71-80',
       'More than 100 Days', '81-90', '61-70', '91-100'], dtype=object)

In [8]:
df[df['Stay'].isin(['More than 100 Days'])].count()

case_id                              6683
Hospital_code                        6683
Hospital_type_code                   6683
City_Code_Hospital                   6683
Hospital_region_code                 6683
Available Extra Rooms in Hospital    6683
Department                           6683
Ward_Type                            6683
Ward_Facility_Code                   6683
Bed Grade                            6681
patientid                            6683
City_Code_Patient                    6550
Type of Admission                    6683
Severity of Illness                  6683
Visitors with Patient                6683
Age                                  6683
Admission_Deposit                    6683
Stay                                 6683
dtype: int64

In [9]:
df.describe().T

count           mean           std  \
case_id                            318438.0  159219.500000  91925.276847   
Hospital_code                      318438.0      18.318841      8.633755   
City_Code_Hospital                 318438.0       4.771717      3.102535   
Available Extra Rooms in Hospital  318438.0       3.197627      1.168171   
Bed Grade                          318325.0       2.625807      0.873146   
patientid                          318438.0   65747.579472  37979.936440   
City_Code_Patient                  313906.0       7.251859      4.745266   
Visitors with Patient              318438.0       3.284099      1.764061   
Admission_Deposit                  318438.0    4880.749392   1086.776254   

                                      min       25%       50%        75%  \
case_id                               1.0  79610.25  159219.5  238828.75   
Hospital_code                         1.0     11.00      19.0      26.00   
City_Code_Hospital                    1.0      2.00       5.0       7.00   
Available Extra Rooms in Hospital     0.0      2.00       3.0       4.00   
Bed Grade                             1.0      2.00       3.0       3.00   
patientid                             1.0  32847.00   65724.5   98470.00   
City_Code_Patient                     1.0      4.00       8.0       8.00   
Visitors with Patient                 0.0      2.00       3.0       4.00   
Admission_Deposit                  1800.0   4186.00    4741.0    5409.00   

                                        max  
case_id                            318438.0  
Hospital_code                          32.0  
City_Code_Hospital                     13.0  
Available Extra Rooms in Hospital      24.0  
Bed Grade                               4.0  
patientid                          131624.0  
City_Code_Patient                      38.0  
Visitors with Patient                  32.0  
Admission_Deposit                   11008.0

In [10]:
df_prepare = df.copy()
df_prepare['avg_age'] = df_prepare['Age'].apply(convert_age_to_num)
df_prepare['avg_stay'] = df_prepare['Stay'].apply(convert_age_to_num)

In [11]:
df_prepare = df_prepare.copy().drop(['Age', 'Stay'], axis=1)

In [12]:
df_prepare.head()

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   
2        3             10                  e                   1   
3        4             26                  b                   2   
4        5             26                  b                   2   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   
2                    X                                  2    anesthesia   
3                    Y                                  2  radiotherapy   
4                    Y                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   
2         S                  E        2.0      31397                7.0   
3         R                  D        2.0      31397                7.0   
4         S                  D        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient  \
0         Emergency             Extreme                      2   
1            Trauma             Extreme                      2   
2            Trauma             Extreme                      2   
3            Trauma             Extreme                      2   
4            Trauma             Extreme                      2   

   Admission_Deposit  avg_age  avg_stay  
0             4911.0     55.5       5.0  
1             5954.0     55.5      45.5  
2             4745.0     55.5      35.5  
3             7272.0     55.5      45.5  
4             5558.0     55.5      45.5

In [13]:
df_prepare.corr().T

case_id  Hospital_code  \
case_id                            1.000000      -0.043023   
Hospital_code                     -0.043023       1.000000   
City_Code_Hospital                -0.011352       0.128294   
Available Extra Rooms in Hospital  0.042580      -0.059638   
Bed Grade                          0.013702      -0.013739   
patientid                         -0.004150       0.002291   
City_Code_Patient                  0.065196      -0.015530   
Visitors with Patient              0.001309      -0.028500   
Admission_Deposit                 -0.045972       0.045446   
avg_age                           -0.114852       0.016332   
avg_stay                          -0.060092       0.040198   

                                   City_Code_Hospital  \
case_id                                     -0.011352   
Hospital_code                                0.128294   
City_Code_Hospital                           1.000000   
Available Extra Rooms in Hospital           -0.045771   
Bed Grade                                   -0.049309   
patientid                                    0.000750   
City_Code_Patient                           -0.023988   
Visitors with Patient                        0.018184   
Admission_Deposit                           -0.034455   
avg_age                                      0.020495   
avg_stay                                     0.007011   

                                   Available Extra Rooms in Hospital  \
case_id                                                     0.042580   
Hospital_code                                              -0.059638   
City_Code_Hospital                                         -0.045771   
Available Extra Rooms in Hospital                           1.000000   
Bed Grade                                                  -0.115868   
patientid                                                   0.000921   
City_Code_Patient                                          -0.009681   
Visitors with Patient                                       0.096714   
Admission_Deposit                                          -0.143739   
avg_age                                                    -0.133227   
avg_stay                                                   -0.107739   

                                   Bed Grade  patientid  City_Code_Patient  \
case_id                             0.013702  -0.004150           0.065196   
Hospital_code                      -0.013739   0.002291          -0.015530   
City_Code_Hospital                 -0.049309   0.000750          -0.023988   
Available Extra Rooms in Hospital  -0.115868   0.000921          -0.009681   
Bed Grade                           1.000000   0.001645          -0.008105   
patientid                           0.001645   1.000000           0.002002   
City_Code_Patient                  -0.008105   0.002002           1.000000   
Visitors with Patient               0.088945   0.006889          -0.012074   
Admission_Deposit                   0.073833  -0.000877           0.025837   
avg_age                             0.001635  -0.001500          -0.016451   
avg_stay                            0.002589   0.000875          -0.012547   

                                   Visitors with Patient  Admission_Deposit  \
case_id                                         0.001309          -0.045972   
Hospital_code                                  -0.028500           0.045446   
City_Code_Hospital                              0.018184          -0.034455   
Available Extra Rooms in Hospital               0.096714          -0.143739   
Bed Grade                                       0.088945           0.073833   
patientid                                       0.006889          -0.000877   
City_Code_Patient                              -0.012074           0.025837   
Visitors with Patient                           1.000000          -0.150358   
Admission_Deposit                              -0.150358           1.000000   
avg_age       

In [14]:
len(df[df_prepare['avg_stay'].isin(['More than 100 Days'])])

0

In [15]:
df_prepare.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318438 entries, 0 to 318437
Data columns (total 18 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   case_id                            318438 non-null  int64  
 1   Hospital_code                      318438 non-null  int64  
 2   Hospital_type_code                 318438 non-null  object 
 3   City_Code_Hospital                 318438 non-null  int64  
 4   Hospital_region_code               318438 non-null  object 
 5   Available Extra Rooms in Hospital  318438 non-null  int64  
 6   Department                         318438 non-null  object 
 7   Ward_Type                          318438 non-null  object 
 8   Ward_Facility_Code                 318438 non-null  object 
 9   Bed Grade                          318325 non-null  float64
 10  patientid                          318438 non-null  int64  
 11  City_Code_Patient                  3139

In [16]:
df_prepare['avg_stay'] = df_prepare['avg_stay'].fillna(100)

In [17]:
df_prepare.columns

Index(['case_id', 'Hospital_code', 'Hospital_type_code', 'City_Code_Hospital',
       'Hospital_region_code', 'Available Extra Rooms in Hospital',
       'Department', 'Ward_Type', 'Ward_Facility_Code', 'Bed Grade',
       'patientid', 'City_Code_Patient', 'Type of Admission',
       'Severity of Illness', 'Visitors with Patient', 'Admission_Deposit',
       'avg_age', 'avg_stay'],
      dtype='object')

In [ ]:
sns.pairplot(df_prepare)

In [19]:
print(df_prepare['case_id'].unique())
print('**************************************************************')
print(df_prepare['Hospital_code'].unique())
print('**************************************************************')
print(df_prepare['Hospital_type_code'].unique())
print('**************************************************************')
print(df_prepare['City_Code_Hospital'].unique())
print('**************************************************************')
print(df_prepare['Hospital_region_code'].unique())
print('**************************************************************')
print(df_prepare['Available Extra Rooms in Hospital'].unique())
print('**************************************************************')
print(df_prepare['Ward_Type'].unique())
print('**************************************************************')
print(df_prepare['Ward_Facility_Code'].unique())
print('**************************************************************')
print(df_prepare['Bed Grade'].unique())
print('**************************************************************')
print(df_prepare['patientid'].unique())
print('**************************************************************')
print(df_prepare['City_Code_Patient'].unique())
print('**************************************************************')
print(df_prepare['Type of Admission'].unique())
print('**************************************************************')
print(df_prepare['Severity of Illness'].unique())
print('**************************************************************')
print(df_prepare['Visitors with Patient'].unique())
print('**************************************************************')
print(df_prepare['Admission_Deposit'].unique())
print('**************************************************************')
print(df_prepare['avg_age'].unique())
print('**************************************************************')
print(df_prepare['avg_stay'].unique())
print('**************************************************************')

[     1      2      3 ... 318436 318437 318438]
**************************************************************
[ 8  2 10 26 23 32  1 22 16  9  6 29 12  3 21 28 27 19  5 14 13 31 24 17
 25 15 11 30 18  4  7 20]
**************************************************************
['c' 'e' 'b' 'a' 'f' 'd' 'g']
**************************************************************
[ 3  5  1  2  6  9 10  4 11  7 13]
**************************************************************
['Z' 'X' 'Y']
**************************************************************
[ 3  2  1  4  6  5  7  8  9 10 12  0 11 20 14 21 13 24]
**************************************************************
['R' 'S' 'Q' 'P' 'T' 'U']
**************************************************************
['F' 'E' 'D' 'B' 'A' 'C']
**************************************************************
[ 2.  3.  4.  1. nan]
**************************************************************
[ 31397  63418   8088 ... 125235  91081  21641]
*****************************

In [20]:
df_prepare.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318438 entries, 0 to 318437
Data columns (total 18 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   case_id                            318438 non-null  int64  
 1   Hospital_code                      318438 non-null  int64  
 2   Hospital_type_code                 318438 non-null  object 
 3   City_Code_Hospital                 318438 non-null  int64  
 4   Hospital_region_code               318438 non-null  object 
 5   Available Extra Rooms in Hospital  318438 non-null  int64  
 6   Department                         318438 non-null  object 
 7   Ward_Type                          318438 non-null  object 
 8   Ward_Facility_Code                 318438 non-null  object 
 9   Bed Grade                          318325 non-null  float64
 10  patientid                          318438 non-null  int64  
 11  City_Code_Patient                  3139

In [21]:
df_prepare.quantile(0.95)

case_id                              302516.15
Hospital_code                            30.00
City_Code_Hospital                       11.00
Available Extra Rooms in Hospital         5.00
Bed Grade                                 4.00
patientid                            125106.00
City_Code_Patient                        16.00
Visitors with Patient                     6.00
Admission_Deposit                      6926.00
avg_age                                  75.50
avg_stay                                 75.50
Name: 0.95, dtype: float64

In [ ]:
sns.heatmap(df_prepare.isna(), annot=True, fmt="d")